# Generated by Django 3.1.12 on 2025-04-02 15:42

from django.db import migrations

def add_default_categories(apps, schema_editor):
    Category = apps.get_model('Myapp', 'Category')
    User = apps.get_model('auth', 'User')

    default_categories = [
        {'name': 'Ăn uống', 'color': '#2ecc71', 'type': 'expense'},
        {'name': 'Đi lại', 'color': '#3498db', 'type': 'expense'},
        {'name': 'Sinh hoạt', 'color': '#e74c3c', 'type': 'expense'},
        {'name': 'Lương', 'color': '#f1c40f', 'type': 'income'},
        {'name': 'Khác', 'color': '#9b59b6', 'type': 'income'},
    ]

    # Lấy tất cả user trong hệ thống
    users = User.objects.all()
    if not users:
        print("No users found in the system.")
        return

    for user in users:
        for category_data in default_categories:
            # Chỉ tạo nếu danh mục chưa tồn tại cho user này
            if not Category.objects.filter(name=category_data['name'], owner=user).exists():
                Category.objects.create(
                    name=category_data['name'],
                    color=category_data['color'],
                    type=category_data['type'],
                    owner=user
                )
                print(f"Created category '{category_data['name']}' for user '{user.username}'")
class Migration(migrations.Migration):
    dependencies = [ ('Myapp', '0004_category_type'),]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
