# Generated by Django 3.1.12 on 2025-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], default='expense', max_length=10),
        ),
    ]
